version: "3.7"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DATABASE: ${APP_DB_DATABASE}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dcard-networks
    volumes:
      - ./.volumes/db:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    restart: always
    environment:
      TZ: ${APP_SERVER_TIMEZONE}
    ports:
      - ${APP_REDIS_PORT}:6379
    networks:
      - dcard-networks
    volumes:
      - ./.volumes/redis:/data

networks:
  dcard-networks:
    driver: bridge