definitions:
  dcard-backend-2024_pkg_model.Ad:
    properties:
      age_end:
        type: integer
      age_start:
        type: integer
      content:
        type: string
      country:
        items:
          type: string
        type: array
      end_at:
        type: string
      gender:
        items:
          type: string
        type: array
      id:
        type: string
      platform:
        items:
          type: string
        type: array
      start_at:
        type: string
      title:
        type: string
      version:
        description: Version log index(offset) in the redis stream
        type: integer
    type: object
  dcard-backend-2024_pkg_model.CreateAdRequest:
    properties:
      age_end:
        type: integer
      age_start:
        type: integer
      content:
        type: string
      country:
        items:
          type: string
        type: array
      end_at:
        type: string
      gender:
        items:
          type: string
        type: array
      platform:
        items:
          type: string
        type: array
      start_at:
        type: string
      title:
        type: string
    required:
    - age_end
    - age_start
    - content
    - country
    - end_at
    - gender
    - platform
    - start_at
    - title
    type: object
  dcard-backend-2024_pkg_model.CreateAdResponse:
    properties:
      data:
        description: Data id of the created ad
        type: string
      msg:
        type: string
    type: object
  dcard-backend-2024_pkg_model.GetAdsPageResponse:
    properties:
      ads:
        items:
          $ref: '#/definitions/dcard-backend-2024_pkg_model.Ad'
        type: array
      total:
        type: integer
    type: object
  dcard-backend-2024_pkg_model.Response:
    properties:
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/ad:
    get:
      consumes:
      - application/json
      description: Retrieves an ad by ID
      parameters:
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Limit for pagination
        in: query
        name: limit
        type: integer
      - description: Age
        in: query
        name: age
        type: integer
      - description: Gender
        in: query
        name: gender
        type: string
      - description: Country
        in: query
        name: country
        type: string
      - description: Platform
        in: query
        name: platform
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.GetAdsPageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.Response'
      summary: Get an ad by ID
      tags:
      - Ad
    post:
      consumes:
      - application/json
      description: Create an ad
      parameters:
      - description: Ad object
        in: body
        name: ad
        required: true
        schema:
          $ref: '#/definitions/dcard-backend-2024_pkg_model.CreateAdRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.CreateAdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dcard-backend-2024_pkg_model.Response'
      summary: Create an ad
      tags:
      - Ad
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
