env:
  DOMAIN: dcard-backend-intern-2024.peterxcli.dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: public/docs
          spec-file: docs/swagger.json

      - name: Test and Coverage
        run: |
          mkdir -p public/coverage
          make test
          go tool cover -html=coverage.out -o public/coverage/index.html
        env:
          APP_REDIS_HOST: localhost
          APP_REDIS_PORT: 6379

      - name: Setup CNAME
        run: echo $DOMAIN > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
